cask "font-ibm-plex-mono-kg" do
  version "2.6.30"
  sha256 "6151df7315ef5389efecfa9be73a5424803994b393f10cc0308463526405a155"
  url "https://github.com/kaushikgopal/ibm-plex-mono-kg/releases/download/2.6.30/ibm-plex-mono-kg-2.6.30.zip"
  name "IBM Plex Mono Font KG"
  homepage "https://kau.sh/blog/freeze-alt-char-open-type-font/"

  font "IBMPlexMono-Bold-KG.otf"
  font "IBMPlexMono-BoldItalic-KG.otf"
  font "IBMPlexMono-ExtraLight-KG.otf"
  font "IBMPlexMono-ExtraLightItalic-KG.otf"
  font "IBMPlexMono-Italic-KG.otf"
  font "IBMPlexMono-Light-KG.otf"
  font "IBMPlexMono-LightItalic-KG.otf"
  font "IBMPlexMono-Medium-KG.otf"
  font "IBMPlexMono-MediumItalic-KG.otf"
  font "IBMPlexMono-Regular-KG.otf"
  font "IBMPlexMono-SemiBold-KG.otf"
  font "IBMPlexMono-SemiBoldItalic-KG.otf"
  font "IBMPlexMono-Text-KG.otf"
  font "IBMPlexMono-TextItalic-KG.otf"
  font "IBMPlexMono-Thin-KG.otf"
  font "IBMPlexMono-ThinItalic-KG.otf"

end
