cask "font-ibm-plex-mono-kg" do
  version "1.6.30"
  sha256 "8d823383e7750954da3bbbd024d002e92aa1f5de23770125428a1c53ae5a4423"
  url "https://github.com/kaushikgopal/homebrew-tools/releases/download/font-ibm-plex-mono-kg-1.6.30/ibm-plex-mono-kg-1.6.30.zip"
  name "IBM Plex Mono Font KG"
  homepage "https://kau.sh/blog/freeze-alt-char-open-type-font/"

  font "IBM-Plex-Mono-KG/IBMPlexMono-Thin.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-Bold.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-SemiBoldItalic.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-Italic.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-TextItalic.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-SemiBold.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-LightItalic.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-ExtraLightItalic.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-Regular.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-Light.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-BoldItalic.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-Text.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-ThinItalic.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-MediumItalic.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-Medium.kg.otf"
  font "IBM-Plex-Mono-KG/IBMPlexMono-ExtraLight.kg.otf"
end
